lib/util.js

urllib中接受到数据为空时不会报错会把data赋值为null，所以在处理时先要判断data是否为空

当前data为null时会直接报错

---

lib/api_js.js

添加计算卡券cardExt签名的jssdk后端api

---

lib/api_common.js
lib/api_custom_service.js

接口变更至https://api.weixin.qq.com/customservice/msgrecord/getrecord?access_token=ACCESS_TOKEN

修复了获取客服聊天记录的接口错误

---

lib/api_device.js

参数optype写错了,详见http://iot.weixin.qq.com/document-2_6.html

设备授权API参数问题修复.

---

lib/api_media.js

增加微信新增加的文章内图片上传API

---

lib/api_card.js

getCards status_list param

---

lib/api_shakearound.js

接口文档地址：http://mp.weixin.qq.com/wiki/12/9738788d171724b080b52f6e41490cb4.html
貌似设备分组管理相关接口还没有成功提交进来

新增摇一摇红包相关接口

---

index.js
lib/api_menu.js
lib/api_menu_custom.js

http://mp.weixin.qq.com/wiki/0/c48ccd12b69ae023159b4bfaa7c39c20.html
新增 个性化菜单 api

add custom menu api

---

lib/api_template.js
test/api_template.test.js

add template method 
* getIndustry
* getAllPrivateTemplate
* delPrivateTemplate
更新了官方文档中的3个API 包括查询所属行业 查询当前帐号的消息模板列表以及删除消息模板的接口

update template api

---

lib/api_card.js

Add: add consumer for card

---

lib/api_template.js

fix 61b656b233094f7966e2f24082e971ebcd7e27e1

template: update topColor compatible sendTemplate()

---

lib/api_media.js

修改返回错误时的消息头类型

---

index.js
lib/api_tag.js
test/api_tag.test.js

tags ops code and test

---

README.md

就是第二个有点不规范地把名字给改了

---

lib/api_card.js
test/api_card.test.js

- 修复了batchget的拼写错误。
- 补全了测试脚本。需要在环境变量重设开通卡卷权限的appid和appsecert在config.js中。

Submerchant

---

lib/api_media.js
test/api_media.test.js

新增流式上传临时媒体资源

---

lib/api_custom_service.js

修复设置客服头像方法中this指向不正确的问题

---

lib/api_qrcode.js

fix typo in qrcode

---

lib/api_message.js

发送消息支持带客服账号

---

lib/api_qrcode.js

@JacksonTian 烦请尽快 review 代码, 如无问题, 请发布一个新的版本, 谢啦

添加创建字符串形式的临时二维码支持
